package com.sameer.employees.Model;
// default package
// Generated Jul 23, 2016 1:52:39 AM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salaries generated by hbm2java
 */
@Entity
@Table(name = "SALARIES", schema = "SCOTT")
public class Salaries implements java.io.Serializable {

	private SalariesId id;
	private Employees employees;
	private long salary;
	private Date toDate;

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "empNo", column = @Column(name = "EMP_NO", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "fromDate", column = @Column(name = "FROM_DATE", nullable = false, length = 7)) })
	public SalariesId getId() {
		return this.id;
	}

	public void setId(SalariesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_NO", nullable = false, insertable = false, updatable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	@Column(name = "SALARY", nullable = false, precision = 10, scale = 0)
	public long getSalary() {
		return this.salary;
	}

	public void setSalary(long salary) {
		this.salary = salary;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TO_DATE", nullable = false, length = 7)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
