package com.sameer.employees.Model;
// default package
// Generated Jul 23, 2016 1:52:39 AM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SalariesId generated by hbm2java
 */
@Embeddable
public class SalariesId implements java.io.Serializable {

	private long empNo;
	private Date fromDate;

	@Column(name = "EMP_NO", nullable = false, precision = 10, scale = 0)
	public long getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(long empNo) {
		this.empNo = empNo;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 7)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalariesId))
			return false;
		SalariesId castOther = (SalariesId) other;

		return (this.getEmpNo() == castOther.getEmpNo())
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEmpNo();
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
