package com.sameer.employees.Model;
// default package
// Generated Jul 23, 2016 1:52:39 AM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeptManagerId generated by hbm2java
 */
@Embeddable
public class DeptManagerId implements java.io.Serializable {

	private long empNo;
	private String deptNo;

	
	@Column(name = "EMP_NO", nullable = false, precision = 10, scale = 0)
	public long getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(long empNo) {
		this.empNo = empNo;
	}

	@Column(name = "DEPT_NO", nullable = false, length = 4)
	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeptManagerId))
			return false;
		DeptManagerId castOther = (DeptManagerId) other;

		return (this.getEmpNo() == castOther.getEmpNo())
				&& ((this.getDeptNo() == castOther.getDeptNo()) || (this.getDeptNo() != null
						&& castOther.getDeptNo() != null && this.getDeptNo().equals(castOther.getDeptNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEmpNo();
		result = 37 * result + (getDeptNo() == null ? 0 : this.getDeptNo().hashCode());
		return result;
	}

}
